name: cd
on:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Qemu
        uses: docker/setup-qemu-action@v1
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azifaazka/vaccinecapsdua:latest
      - name: ssh aws ec2 and redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            docker login -u azifaazka -p Azumiya18
            docker stop vaccinecapsdua
            docker container rm vaccinecapsdua
            docker pull azifaazka/vaccinecapsdua:latest
            docker run -e DB_HOST="database-4.cn1x7ayh0czt.us-west-1.rds.amazonaws.com" -e DB_USERNAME="admin" -e DB_PASSWORD="XmNP9Y5DQC2rUVsz4sDi" -e DB_NAME="vaccine" -e DB_PORT="3306" -e JWT_KEY="ABC" -e APP_HOST="13.57.43.205" -p 8080:80 --name vaccinecapsdua --detach azifaazka/vaccinecapsdua:latest
