name: cd
on:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Qemu
        uses: docker/setup-qemu-action@v1
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azifaazka/vaccinecaps2:latest
      - name: ssh aws ec2 and redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            docker login -u azifaazka -p Azumiya18
            docker pull azifaazka/vaccinecaps2:latest
            docker run -d -p 80:8080 --name vaccinecaps2 azifaazka/vaccinecaps2:latest
